import { Pedido } from '../types';

export const SEED: Pedido[] = [
  { id: '001', num: '001', data: '03/01/2026', cliente: 'Academia FitPower',      nomePedidoOriginal: 'Boné Snapback',    cor: 'Preto Aba Preta',    qtd: 100, numeroSistema: 'W001', tecnica: 'Bordado 3D',          status_producao: 'Em Produção', status_pgto: 'PAGO',     entrega: '20/01/2026', observacoes: '' },
  { id: '002', num: '002', data: '10/01/2026', cliente: 'Time Atlético FC',        nomePedidoOriginal: 'Boné Baseball',    cor: 'Vermelho/Branco',    qtd: 50,  numeroSistema: 'W002', tecnica: 'Bordado',             status_producao: 'Entregue',    status_pgto: 'PAGO',     entrega: '25/01/2026', observacoes: 'Entregue no prazo' },
  { id: '003', num: '003', data: '15/01/2026', cliente: 'Escola Municipal Verde',  nomePedidoOriginal: 'Boné Dad Hat',     cor: 'Verde/Branco',       qtd: 180, numeroSistema: 'W003', tecnica: 'Silk Screen',         status_producao: 'Aguardando',  status_pgto: 'PENDENTE', entrega: '05/02/2026', observacoes: 'Aguardando aprovação da arte' },
  { id: '004', num: '004', data: '20/01/2026', cliente: 'Construtora Nordeste',    nomePedidoOriginal: 'Boné Militar',     cor: 'Laranja Neon',       qtd: 80,  numeroSistema: 'W004', tecnica: 'Bordado',             status_producao: 'Em Produção', status_pgto: 'PARCIAL',  entrega: '10/02/2026', observacoes: 'Logo frontal + lateral esquerda' },
  { id: '005', num: '005', data: '01/02/2026', cliente: 'StreetWear Store',        nomePedidoOriginal: 'Boné Trucker',     cor: 'Preto/Malha Branca', qtd: 60,  numeroSistema: 'W005', tecnica: 'Patch Emborrachado',  status_producao: 'ATRASADO',    status_pgto: 'PENDENTE', entrega: '15/01/2026', observacoes: 'Cliente cobrando entrega' },
  { id: '006', num: '006', data: '10/02/2026', cliente: 'Sorveteria Gelato',       nomePedidoOriginal: 'Boné Dad Hat',     cor: 'Rosa Pastel',        qtd: 30,  numeroSistema: 'W006', tecnica: 'Bordado',             status_producao: 'Em Produção', status_pgto: 'PAGO',     entrega: '28/02/2026', observacoes: 'Arte com sorvete estilizado' },
  { id: '007', num: '007', data: '15/02/2026', cliente: 'Festival Sons do Norte',  nomePedidoOriginal: 'Bucket Hat',       cor: 'Tie-Dye Multicolor', qtd: 120, numeroSistema: 'W007', tecnica: 'Sublimação',          status_producao: 'Enviado',     status_pgto: 'PAGO',     entrega: '25/02/2026', observacoes: 'Enviado via Sedex' },
  { id: '008', num: '008', data: '01/03/2026', cliente: 'Pousada Sol & Mar',       nomePedidoOriginal: 'Viseira Esportiva',cor: 'Azul Royal',         qtd: 40,  numeroSistema: 'W008', tecnica: 'Bordado 3D',          status_producao: 'Em Produção', status_pgto: 'PAGO',     entrega: '25/06/2026', observacoes: '' },
  { id: '009', num: '009', data: '05/03/2026', cliente: 'Tech Corp Brasil',        nomePedidoOriginal: 'Boné Snapback',    cor: 'Preto Total',        qtd: 200, numeroSistema: 'W009', tecnica: 'Patch Emborrachado',  status_producao: 'Aguardando',  status_pgto: 'PENDENTE', entrega: '30/06/2026', observacoes: 'Aguardando aprovação e NF' },
];
